
services:
  minecraft:
    container_name: purpur-server
    build:
      context: .
      args:
        MC_UID: ${MC_UID:-1000}
        MC_GID: ${MC_GID:-1000}
        MC_VERSION: ${MC_VERSION}

    ports:
      - "${MC_PORT}:25565"

    environment:
      RAM: "3G"
      # from flags.sh built using Aikar's Flags
      JAVAFLAGS: >
        --add-modules=jdk.incubator.vector
        -XX:+ParallelRefProcEnabled
        -XX:MaxGCPauseMillis=200
        -XX:+DisableExplicitGC
        -XX:+AlwaysPreTouch
        -XX:G1HeapWastePercent=5
        -XX:G1MixedGCCountTarget=4
        -XX:InitiatingHeapOccupancyPercent=15
        -XX:G1MixedGCLiveThresholdPercent=90
        -XX:G1RSetUpdatingPauseTimePercent=5
        -XX:SurvivorRatio=32
        -XX:+PerfDisableSharedMem
        -XX:MaxTenuringThreshold=1
        -Dusing.aikars.flags=https://mcflags.emc.gs
        -Daikars.new.flags=true
        -XX:G1NewSizePercent=30
        -XX:G1MaxNewSizePercent=40
        -XX:G1HeapRegionSize=8M 
        -XX:G1ReservePercent=20

      TZ: "America/Toronto"

    volumes:
      - ./data:/data:rw

    restart: unless-stopped
    stdin_open: true
    tty: true
